### ISSUE TITLE
ACL, Metadata, etc not registering in uploaded object.

### ISSUE THREAD

**Issue by krrishd** [RiptideElements/s3fs#154]
```javascript
var s3fsImplementation = new s3fs('bucketname', {
	accessKeyId: AWS_ACCESS_KEY_ID,
	secretAccessKey: AWS_SECRET_ACCESS_KEY,
	ACL: 'public-read',
	ContentType: 'image/png'
});
```

^ with that implementation, somehow the object successfully uploads to S3, but **neither the specified ACL nor the Content-Type are registered in said uploaded object**. I'm pretty sure this isn't a policy error either, as the policy I've attached to the relevant user is as follows:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmtxxxxxxxxxxxxxx",
      "Effect": "Allow",
      "Action": [
        "s3:AbortMultipartUpload",
        "s3:CreateBucket",
        "s3:DeleteBucket",
        "s3:DeleteBucketPolicy",
        "s3:DeleteObject",
        "s3:GetBucketAcl",
        "s3:GetBucketPolicy",
        "s3:GetLifecycleConfiguration",
        "s3:GetObject",
        "s3:GetObjectAcl",
        "s3:ListBucket",
        "s3:ListBucketMultipartUploads",
        "s3:ListMultipartUploadParts",
        "s3:PutBucketAcl",
        "s3:PutBucketPolicy",
        "s3:PutLifecycleConfiguration",
        "s3:PutObject",
        "s3:PutObjectAcl"
      ],
      "Resource": [
        "arn:aws:s3:::[bucket_name_redacted]/*"
      ]
    },
    {
      "Sid": "Stmtxxnxxxxxxxxxxxxx",
      "Effect": "Allow",
      "Action": [
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:was:s3:::[bucket_name_redacted]"
      ]
    }
  ]
}
```

Just wanted to know whether I was perhaps doing something wrong, since I couldn't find anything specifically wrong based on the documentation available.

**Comment by DavidTPate** [comment]
Hi there!

I'm a little confused as to what you are attempting to do here, as the code you have provided is only the code for setting up the initial connection to S3. It doesn't do any uploading or anything like that. Could you provide more complete code example of what you are doing?

For a generic example if I wanted to write a file to S3 with the ACL of `public-read` and a content type of `image/png` I would do the following:

```js
const fsImpl = new S3fs('my-cool-bucket');
fsImpl.writeFile('some/image.png', myImageStream, {
    ACL: 'public-read',
    ContentType: 'image/png'
});
```

**Comment by krrishd** [comment]
Hey there,

I didn't pay enough attention to the docs where it said that [options] were a third parameter in writeFile, so I assumed I could pass default values (which I now see isn't the case). Your example works perfect, sorry for the confusion

**Comment by DavidTPate** [comment]
Not a problem, let me know if you run into more issues!
