### ISSUE TITLE
How to retrieve image from s3?

### ISSUE THREAD

**Issue by stoplion** [RiptideElements/s3fs#183]
Trying to retrieve images from S3. The documentation is not clear how to do this.

```
let filePath = 'https://test.s3.amazonaws.com/2016_8_2/e21ccf2144df91bf6baab69d6ab0017e.png';

S3Client.readFile(filePath).then(
      (d) => {
        console.log(d);
      }, (err) => {
        console.log(err);
      });
```

Neither the error or success are run...

[SO Question](http://stackoverflow.com/questions/39484911/using-s3fs-node-module-how-can-i-retrieve-the-images-from-s3)

**Comment by DavidTPate** [comment]
Please take a look at the [documentation](https://github.com/RiptideElements/s3fs#example-promise-usage) which has multiple examples of usage of the module.

In the case of what you are attempting to do you appear to be using an absolute URL to retrieve a file from this which won't work. Think of this like it is a replacement for [FS](https://nodejs.org/api/fs.html) and use it that same way.

**Comment by stoplion** [comment]
Thanks. Lots on info on reading, but none on writing in that link above..

**Comment by DavidTPate** [comment]
[Writing files](https://github.com/RiptideElements/s3fs#example-promise-usage)

```js
var S3FS = require('s3fs');
var fsImpl = new S3FS('test-bucket', options);
fsImpl.writeFile('message.txt', 'Hello Node').then(function() {
  console.log('It\'s saved!');
}, function(reason) {
  throw reason;
});
```

As mentioned in the documentation there, enjoy!
