### ISSUE TITLE
Using Pre-Signed URL

### ISSUE THREAD

**Issue by paulxtiseo** [RiptideElements/s3fs#187]
Is it possible to use this library to upload a file to a pre-signed URL without setting keys and secrets? If so, how? (Even better if you teach me how to upload a large file also. :) ) My hanging point is that I don't want to give away the keys by doing a:
```
let s3fsImpl = new S3FS('mybucketname', {
  accessKeyId: XXXXXXXXXXX,
  secretAccessKey: XXXXXXXXXXXXXXXXX
});
```

**Comment by DavidTPate** [comment]
For pre-signed URLs this module won't work for that as a pre-signed URL would only give you access to a single thing.

I'm not sure what you mean by doing that would give away your keys. What happens is that the keys that you provide (or IAM role on your instance or [other configuration values](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html) that the AWS SDK supports) are used to generate signatures via HMAC that are used to communicate with the AWS services. For more details you can check out the [AWS SDK](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-intro.html) documentation to see what AWS says about it.
