### ISSUE TITLE
Cannot set acl on file upload

### ISSUE THREAD

**Issue by Ajaay** [RiptideElements/s3fs#207]
I need to be able to set the acl type against a file when uploaded like so:

s3fsImpl = new S3FS('test', {
		        accessKeyId: 'XXXXX',
		        secretAccessKey: 'XXXXXX',
		        region: 'us-west-1',
		        acl: 'public-read',
		    });

This is a supported option under the aws-sdk but doesn't appear to be working. I've tried acl capitalised as well but it doesn't appear to make a difference.

Is this possible using this package?

Thanks

**Comment by TylerDixon** [comment]
I believe this is a similar issue to #154. See the comment [here](https://github.com/RiptideElements/s3fs/issues/154#issuecomment-238270303) for writing a file with a specified ACL.

**Comment by Ajaay** [comment]
Yep that's fixed it! As with the other guy - sorry for not reading the documentation properly :)

Thanks!
