### ISSUE TITLE
get file PATH after upload

### ISSUE THREAD

**Issue by DThink** [RiptideElements/s3fs#208]
hi, there are a method to get the file URL after having upload it? i see that after the upload the write file function retrive only the `ETag` but i need to have a URL to store in the database. i can construct it by the `getPath() `method

**Comment by techverx** [comment]
Hi @DThink , have you got the file path after upload file on s3. I am having the same issue that how I got public path after upload because I want to save that path in database. 

Thanks :)

**Comment by TylerDixon** [comment]
Correct, `getPath()` would be the proper method for retrieving the location of a file following upload, you would just have to pre-pend the returned string with `https://s3.amazonaws.com/`.

e.g
```js
s3fsImpl.writeFile(somePath, someData).then(function (res) => {
    var itemUrl = 'https://s3.amazonaws.com/' + s3fsImpl.getPath(somePath);
});
```

I'm going to close this, but feel free to let me know if this doesn't work for you and I can look into it more.
