### ISSUE TITLE
2.0.0 Release Notes

### ISSUE THREAD

**Issue by DavidTPate** [RiptideElements/s3fs#21]
# Summary
S3FS 2.0.0 changes how the module is instantiated, update the names of some of the methods that previously existed, enhances some current functionality with support for encoding, and switches from using the Q promise library to Bluebird.

* Upgrade time: low, the changes are minimal and straightforward
* Complexity: low, the changes are pretty straightforward
* Risk: low, the changes to the underlying code is minimal

# Breaking Changes

## Instantiation
Previously instantiating the module was done with the following method signature: `S3FS(options, bucket)` this has been updated to the following `S3FS(bucket, options)`. The update occurred because the AWS SDK that this library relies upon has multiple methods for retrieving the AWS credentials used to connect to S3. One of which is to pass in options, but options are by no means required.

## Copy Directory
`s3fs.copyDirectory(sourcePath, destinationPath[, callback])` has been renamed to `s3fs.copyDir(sourcePath, destinationPath[, callback])` to bring this library inline with available [FS mixins](https://github.com/RiptideCloud/node-fs-wishlist) and provide an optimized path to copying a directory.

## Copy Object
`s3fs.copyObject(sourcePath, destinationPath[, callback])` has been renamed to `s3fs.copyFile(sourcePath, destinationPath[, callback])`  to bring this library inline with available [FS mixins](https://github.com/RiptideCloud/node-fs-wishlist) and provide an optimized path to copying a file.

# New Features
## Write File
`fs.writeFile(filename, data, [options], callback)` now maps a specified `options.encoding` to the S3 parameter when storing a file on S3.

## Read File
`fs.readFile(filename, [options], callback)` now maps a specified `options.encoding` to the S3 parameter to be used when retrieving a file from S3.

# Contributors
The contributors to this release are: me.

**Comment by vbudhram** [comment]
:+1:
