### ISSUE TITLE
Unhandled rejection NoSuchBucket: The specified bucket does not exist

### ISSUE THREAD

**Issue by ishandutta2007** [RiptideElements/s3fs#33]
var AWS_ACCESS_KEY = 'entered my valide key here';
var AWS_SECRET_KEY = 'entered my valid secret here';
var fs = require('fs')
var S3FS = require('s3fs');
var s3fsImpl = new S3FS('entered my valid bucket ame here', { accessKeyId:AWS_ACCESS_KEY, secretAccessKey:AWS_SECRET_KEY });

**Comment by DavidTPate** [comment]
@ishandutta2007 Could you provide some more information on what you are trying to do? I'm wondering where the `Unhandled Rejection` is occurring.

There's a few things that could be going on here, so I have a few questions.
1. What region is your bucket in?
2. Is your bucket name 100% correct? They are case sensitive, and also things like percent encoding are not interpreted. So `my Bucket` is different from `My Bucket` which is different from `my%20Bucket`.

**Comment by Jhorlin** [comment]
@ishandutta2007 are you saying is that his bucket name is incorrect and that s3fs is not handling the fact that the bucket does not exist?

**Comment by ishandutta2007** [comment]
My bad, now it's saving; bucket name was wrong.
