### ISSUE TITLE
Encoding issue for readFile , writeFile works fine.

### ISSUE THREAD

**Issue by ishandutta2007** [RiptideElements/s3fs#37]
var AWS_ACCESS_KEY = 'xxxxxx';
var AWS_SECRET_KEY = 'yyyyyy';
var fs = require('fs');
var S3FS = require('s3fs');
var s3fsImpl = new S3FS("mybucket", {accessKeyId:AWS_ACCESS_KEY,secretAccessKey:AWS_SECRET_KEY});

module.exports.saveCode = function (req, res) {
  s3fsImpl.writeFile('sample_code.py', req.body.codeContent,  {encoding : 'utf8'}, function (err) {
    if (err) throw err;
  });
}

module.exports.fetchCode = function (req, res) {
  s3fsImpl.readFile('sample_code.py',  {encoding : 'utf8'}, function (err, data) {
    if (err) throw err;
    console.log(data);//Here is the issue, it's outputing <Buffer 74 69 74 69 20 3d 20 74 6f 74 6f 0a 74 61 74 61 20 3d 20 74 75 74 75>
  });
}
// In the 2nd argument I tried both  {encoding : 'utf8'} as well as just 'utf8'

**Comment by DavidTPate** [comment]
@ishandutta2007 I'm not able to reproduce your issue. I added a test case for it [here](https://github.com/RiptideElements/s3fs/blob/c311c66ff87ecacbb8b11bcd151ef23675acac48/test/file.js#L128) and it is working as expected. Can you provide the error message you are receiving?

**Comment by Jhorlin** [comment]
:+1: Nice catch.

**Comment by ishandutta2007** [comment]
I am not getting any error; the problem I am facing is similar to this http://stackoverflow.com/questions/15772925/encoding-is-ignored-in-fs-readfile
only difference is for me it's for s3fs and not fs.
I tried the solutions proposed there as I mentioned without any success.

**Comment by DavidTPate** [comment]
@ishandutta2007 I think I understand now. We aren't operating the same as the [FS Interface](https://nodejs.org/api/fs.html#fs_fs_readfile_filename_options_callback). 

Specifically, this part:
> If no encoding is specified, then the raw buffer is returned.

I'll get some tests added around that and a PR also once completed.

**Comment by ishandutta2007** [comment]
But I am using utf8 encoding while writing too.

s3fsImpl.writeFile(fileName, req.body.codeContent,   'utf8', function (err) {
  ...................//
});
s3fsImpl.readFile('sample_code.py',   'utf8', function (err, data) {
    if (err) throw err;
    console.log(bin2String(data));// hack to get it working
});

**Comment by DavidTPate** [comment]
@ishandutta2007 Gotcha, you're using the old call version too. I see that support in the latest NodeJS & iojs releases as well so I'll add that also.

Thanks!

**Comment by DavidTPate** [comment]
@ishandutta2007 We just released the latest version `v2.3.0` which has a fix for the issues that you pointed out in this issue. Thanks for your feedback, let us know if you run into something else!
