### ISSUE TITLE
Wrong mime type on using createWriteStream method

### ISSUE THREAD

**Issue by AScripnic** [RiptideElements/s3fs#46]
Hi, I'm using s3fs to upload a list of files to my s3 repository. I noticed that the files' mime type is wrong (`application/octet-stream`). I'm wondering if there's any possibility to automatically detect mime type or at least manually add it as an option.

**Comment by DavidTPate** [comment]
@AScripnic We could go through and do some magic, but the problem is that it isn't compatible with FS as it doesn't do anything like that.

Check out #45 basically you can do something like this: `s3fs.writeFile(s3Key, stream, {"ContentType":"image/svg+xml", ...});`

**Comment by AScripnic** [comment]
@DavidTPate we arte currently using `s3fs.writeFile` as a workaround, but it's memory consuming for larger files and it's an issue for us due to AWS Lambda price policy.

From my point of view this option is very useful for such kind of cases. We could provide the mime type explicitly when creating the write stream. 

Does it make sense for you?

**Comment by DavidTPate** [comment]
@AScripnic I understand now, I completely glossed over the Stream part of this before. It should still be able to pass the `Content-Type` to the `s3fs.createWriteStream` call, but I don't see a test around it. I'll add a test as an example and to make sure it works.

**Comment by DavidTPate** [comment]
@AScripnic This has just been updated and released. So now you would do something such as the following: `s3fs.createWriteStream(fileName, { ContentType: 'application/json' });` to add the content type. 

AWS has all the supported options here: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html
