### ISSUE TITLE
Public access to files

### ISSUE THREAD

**Issue by aledotgomez** [RiptideElements/s3fs#50]
How can I change the permission type of my uploaded files to be public? Is this related to my s3fs object parameters or do I need to add an IAM policy?

My code is the following:
```
var stream = fs.createReadStream(path);
  s3fsImpl.writeFile(file.originalname, stream).then(function() {
    fs.unlink(path, function(err) {
      if (err) throw err;
    });
    console.log('File successfully uploaded to S3');
  });
```

Thank you. This package rocks btw.

**Comment by DavidTPate** [comment]
Glad you like it!

You can accomplish this with settings being passed to the AWS SDK. You can find all of the available parameters [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property).

In your case you are trying to attach an ACL for Public Read. So, if you were to modify your code like below it would update the file with the Public Read ACL set on it.

```js
var stream = fs.createReadStream(path);
  s3fsImpl.writeFile(file.originalname, stream, {ACL: 'public-read' }).then(function() {
    fs.unlink(path, function(err) {
      if (err) throw err;
    });
    console.log('File successfully uploaded to S3');
  });
```

**Comment by aledotgomez** [comment]
Works like a charm, thanks!
