### ISSUE TITLE
Unclear Docs

### ISSUE THREAD

**Issue by sabrehagen** [RiptideElements/s3fs#52]
When creating an fs implementation via `var fsImpl = new S3FS('test-bucket', options);` the options argument is never explained. I can see further down in the code a "See AWS SDK" link, but it's unclear if this is for the same options object.

Can you please detail the options object format in your documentation?

Thanks!

**Comment by DavidTPate** [comment]
I went through and added a link to the docs for the AWS SDK with the constructor. I'm not going to repeat the documentation that AWS maintains here, but I'll gladly link to it to make it helpful.

**Comment by sabrehagen** [comment]
thank you, much clearer!
