### ISSUE TITLE
headObject Bug

### ISSUE THREAD

**Issue by diegobent** [RiptideElements/s3fs#56]
https://github.com/RiptideElements/s3fs/blob/master/lib/s3fs.js#L485-L486

If I use callback instead of promise, if success callback is invoked without data!

**Comment by DavidTPate** [comment]
All the more reason to not use callbacks :grin:!

Thanks for pointing that out, I'll drop a PR for it. Looks like none of the tests for `headObject` are validating return values so I'll add that so we can catch and regressions.

**Comment by DavidTPate** [comment]
@diegobent I just published `s3fs@2.4.3` to NPM which has this fix in it. Cheers!

**Comment by diegobent** [comment]
Thanks @DavidTPate for the support! :+1: 
Congratulation, for your work! very useful and well done library!  good implemetation and very hight code covarage!
