### ISSUE TITLE
How to remove a file from S3

### ISSUE THREAD

**Issue by AOnurOzcan** [RiptideElements/s3fs#60]
Hi. I am using s3fs for uploading images. I also want to remove files that I uploaded before. How can I do this? Thank you.

**Comment by DavidTPate** [comment]
I'm not sure how your file structure is setup, but you can use [fs.unlink(...)](https://nodejs.org/api/fs.html#fs_fs_unlink_path_callback) which is supported by this library to remove a single file. If instead you need to do some filtering or something there's [fs.readdirp(...)](https://github.com/RiptideElements/s3fs#s3fsreaddirppath-callback) and [fs.rmdirp(...)](https://github.com/RiptideElements/s3fs#s3fsrmdirppath-callback) to recursively read and delete directories.
